// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSmdrLlEcKOBhxfHp2cXsdTB5Le2BNT5Y',
    appId: '1:266444212127:web:3bfc1076845931a730dfaa',
    messagingSenderId: '266444212127',
    projectId: 'elamly-s-market',
    authDomain: 'elamly-s-market.firebaseapp.com',
    storageBucket: 'elamly-s-market.appspot.com',
    measurementId: 'G-VT3FL06848',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB96BVdu2SNQFpelpeYs288b7fE74q5P4M',
    appId: '1:266444212127:android:59cd6ad8ada82b4e30dfaa',
    messagingSenderId: '266444212127',
    projectId: 'elamly-s-market',
    storageBucket: 'elamly-s-market.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_plINsdfPug6KAflRQrkccF9aytHPslM',
    appId: '1:266444212127:ios:5467499c7c9af08230dfaa',
    messagingSenderId: '266444212127',
    projectId: 'elamly-s-market',
    storageBucket: 'elamly-s-market.appspot.com',
    iosClientId: '266444212127-6obfogmemu4hm1pptskkk4o24jm03skg.apps.googleusercontent.com',
    iosBundleId: 'com.example.elamlymarketDashboard',
  );

}